In [37]:
#importing the packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [38]:
#read the files
train_df = pd.read_csv("C:\\Users\\Dell\\Downloads\\Churn_Modelling_Train.csv")
test_df = pd.read_csv("C:\\Users\\Dell\\Downloads\\Churn_Modelling_Test.csv")

In [39]:
train_df.shape

(10000, 14)

In [40]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [41]:
train_df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [42]:
train_df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [43]:
for col in train_df.select_dtypes(include='object').columns:
    print(col)
    print(train_df[col].unique())

Surname
['Hargrave' 'Hill' 'Onio' ... 'Kashiwagi' 'Aldridge' 'Burbidge']
Geography
['France' 'Spain' 'Germany']
Gender
['Female' 'Male']

In [44]:
features_na = [features for features in train_df.columns if train_df[features].isnull().sum() > 0]
for feature in features_na:
    print(feature,np.round(train_df[feature].isnull().mean(),4),'%missing values')
else:
    print('no missing value found')

no missing value found

In [45]:
for column in train_df.columns:
    print(column,train_df[column].nunique())

RowNumber 10000
CustomerId 10000
Surname 2932
CreditScore 460
Geography 3
Gender 2
Age 70
Tenure 11
Balance 6382
NumOfProducts 4
HasCrCard 2
IsActiveMember 2
EstimatedSalary 9999
Exited 2

In [46]:
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels for object columns
train_df['Surname']= label_encoder.fit_transform(train_df['Surname'])
train_df['Surname'].unique()
train_df['Geography']= label_encoder.fit_transform(train_df['Geography'])
train_df['Geography'].unique()
train_df['Gender']= label_encoder.fit_transform(train_df['Gender'])
train_df['Gender'].unique()
test_df['Surname']= label_encoder.fit_transform(test_df['Surname'])
test_df['Surname'].unique()
test_df['Geography']= label_encoder.fit_transform(test_df['Geography'])
test_df['Geography'].unique()
test_df['Gender']= label_encoder.fit_transform(test_df['Gender'])
test_df['Gender'].unique()

array([1, 0])

In [47]:

# splitting the dataset
from sklearn.model_selection import train_test_split
 
predictors = train_df.drop(['Exited','Surname','RowNumber','CustomerId','HasCrCard'], axis=1)

target = train_df["Exited"]
X_train1, X_test, y_train1, y_test = train_test_split(    predictors, target, test_size=0.2, random_state=0)

In [48]:
print("Before OverSampling, counts of label '1': {}".format(sum(y_train1 == 1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train1 == 0)))

# import SMOTE module from imblearn library
# pip install imblearn (if you don't have imblearn in your system)
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 2)
X_train, y_train = sm.fit_resample(X_train1, y_train1.ravel())

print('After OverSampling, the shape of X_train: {}'.format(X_train.shape))
print('After OverSampling, the shape of y_train: {} \n'.format(y_train.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train == 1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train == 0)))

Before OverSampling, counts of label '1': 1632
Before OverSampling, counts of label '0': 6368

After OverSampling, the shape of X_train: (12736, 9)
After OverSampling, the shape of y_train: (12736,)

After OverSampling, counts of label '1': 6368
After OverSampling, counts of label '0': 6368

In [49]:
#logistic regression
from sklearn import linear_model
from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
log_param= {'penalty':['l1', 'l2', 'elasticnet', 'none'],'dual':[0,1],'solver':['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}
scoring= ['accuracy']
log_randm_src = RandomizedSearchCV(estimator=linear_model.LogisticRegression(), param_distributions = log_param,cv = 2,scoring='accuracy', n_iter = 10, n_jobs=-1,verbose=1)
log_randm_src.fit(X_train, y_train)
log_best= log_randm_src.best_score_

Fitting 2 folds for each of 10 candidates, totalling 20 fits

C:\python\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:
14 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\python\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\python\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\python\lib\site-packages\sklearn\linear_model\_logistic.py", line 78, in _check_solver
    raise ValueError("penalty='none' is not supported for the liblinear solver")
ValueError: penalty='none' is not supported for the liblinear solver

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\python\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\python\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\python\lib\site-packages\sklearn\linear_model\_logistic.py", line 66, in _check_solver
    raise ValueError(
ValueError: Solver saga supports only dual=False, got dual=1

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\python\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\python\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\python\lib\site-packages\sklearn\linear_model\_logistic.py", line 61, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only 'l2' or 'none' penalties, got l1 penalty.

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\python\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\python\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\python\lib\site-packages\sklearn\linear_model\_logistic.py", line 66, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only dual=False, got dual=1

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\python\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\python\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\python\lib\site-packages\sklearn\linear_model\_logistic.py", line 66, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only dual=False, got dual=1

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\python\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\python\lib\site-packages\sklearn\linear_model\_logistic.py", line 1101, in fit
    raise ValueError(
ValueError: l1_ratio must be between 0 and 1; got (l1_ratio=None)

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\python\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\python\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\python\lib\site-packages\sklearn\linear_model\_logistic.py", line 61, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got elasticnet penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\python\lib\site-packages\sklearn\model_selection\_search.py:953: UserWarning: One or more of the test scores are non-finite: [0.57121545        nan 0.76531093        nan        nan        nan
        nan        nan        nan 0.5741206 ]
  warnings.warn(

In [50]:
#decision tree classifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
parameters = {'criterion': [ 'gini', 'entropy', 'log_loss'],'max_depth'    : [1,4,5] ,'random_state': [1,5,3]               }
scoring= ['accuracy']
dec_randm_src = RandomizedSearchCV(estimator=model, param_distributions = parameters,scoring='accuracy',cv = 2, n_iter = 10, n_jobs=-1,verbose=1)
dec_randm_src.fit(X_train, y_train)
dec_best=  dec_randm_src.best_score_

Fitting 2 folds for each of 10 candidates, totalling 20 fits

In [51]:
#random forest classifier
from sklearn.ensemble import RandomForestClassifier
regr = RandomForestClassifier(random_state=0, n_jobs=-1)


parameters = {'n_estimators':[10,50,100],'criterion': [ 'gini', 'entropy', 'log_loss'],'max_depth'    : [1,4,5] ,'random_state': [0,5,3] ,'max_features':['sqrt', 'log2', None]}            
scoring= ['accuracy']
ran_randm_src = RandomizedSearchCV(estimator=RandomForestClassifier(), param_distributions = parameters,scoring='accuracy',cv = 2, n_iter = 10, n_jobs=-1,verbose=1)
ran_randm_src.fit(X_train, y_train)

random_best= ran_randm_src.best_score_

Fitting 2 folds for each of 10 candidates, totalling 20 fits

In [52]:
#gradient boosting classifier
from sklearn.ensemble import GradientBoostingClassifier
parameters = {'loss':['log_loss', 'deviance', 'exponential'],'n_estimators':[10,50,100],'criterion': [ 'friedman_mse',  'mse','squared_error'],'max_depth'    : [1,4,5] ,'random_state': [1,5,3]               }
scoring= ['accuracy']
gb_randm_src = RandomizedSearchCV(estimator=GradientBoostingClassifier(), param_distributions = parameters,scoring='accuracy',cv = 2, n_iter = 10, n_jobs=-1,verbose=1)
gb_randm_src.fit(X_train, y_train)

gradient_best= gb_randm_src.best_score_

Fitting 2 folds for each of 10 candidates, totalling 20 fits

In [53]:
#xgboost classifier
from xgboost import XGBClassifier
parameters = {'loss':['log_loss', 'deviance', 'exponential'],'n_estimators':[10,50,100],'criterion': [ 'friedman_mse',  'mse','squared_error'],'max_depth'    : [1,4,5] ,'random_state': [1,5,3]                }
scoring= ['accuracy']
xg_randm_src = RandomizedSearchCV(estimator=XGBClassifier(), param_distributions = parameters,scoring='accuracy',cv = 2, n_iter = 10, n_jobs=-1,verbose=1)
xg_randm_src.fit(X_train, y_train)

XGB_best= xg_randm_src.best_score_

Fitting 2 folds for each of 10 candidates, totalling 20 fits
[17:13:26] WARNING: C:/Users/administrator/workspace/xgboost-win64_release_1.6.0/src/learner.cc:627:
Parameters: { "criterion", "loss" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.

In [54]:
from sklearn.neighbors import KNeighborsClassifier
parameters = {'n_neighbors' : [20,5,10],'weights':['uniform', 'distance'] ,'algorithm':['auto', 'ball_tree', 'kd_tree','brute']}
clf = KNeighborsClassifier()
knn_randm_src = RandomizedSearchCV(estimator=clf, param_distributions = parameters,scoring='accuracy',cv = 2, n_iter = 10, n_jobs=-1,verbose=1)

knn_randm_src .fit(X_train, y_train)
knn_best= knn_randm_src.best_score_

Fitting 2 folds for each of 10 candidates, totalling 20 fits

In [55]:
df = {'method':['logistic_regression','decisiontree_classifier','randomforest_classifier','gradientboost_classifier','XGB_classifier','knn_clasifier'],'Best_accuracy_using_randomized_mtd':[log_best,dec_best,random_best,gradient_best,XGB_best,knn_best]}
df1 = pd.DataFrame(df)
  
# displaying the DataFrame
print('DataFrame:\n', df1)

DataFrame:
                      method  Best_accuracy_using_randomized_mtd
0       logistic_regression                            0.765311
1   decisiontree_classifier                            0.782506
2   randomforest_classifier                            0.802450
3  gradientboost_classifier                            0.818938
4            XGB_classifier                            0.835192
5             knn_clasifier                            0.700141

In [56]:

df2 = {log_randm_src:log_best,dec_randm_src:dec_best,ran_randm_src:random_best,gb_randm_src:gradient_best,xg_randm_src:XGB_best}
  
Keymax = max(zip(df2.values(), df2.keys()))[1]

In [57]:

ids = test_df['CustomerId']
predictions = Keymax.predict(test_df.drop(['HasCrCard' ,'Surname','RowNumber','CustomerId'], axis=1))
 
# set the output as a dataframe

output = pd.DataFrame({'CustomerId': ids, 'Exited': predictions})
output

   CustomerId  Exited
0           1       1
1           2       1
2           3       0
3           4       0
4           5       1

In [58]:
# to csv file named resultfile.csv
output.to_csv('resultfile.csv', index=True)